all: remove status_tv turn_on turn_off volume channel

remove:
	rm -fr status_tv turn_on turn_off volume channel

status_tv:
	gcc status_tv.c -o status_tv

turn_on:
	gcc turn_on_tv.c -o turn_on

turn_off:
	gcc turn_off_tv.c -o turn_off

volume:
	gcc volume_tv.c -o volume

channel:
	gcc channel_tv.c -o channel

