all: remove status_term turn_on turn_off temperature

remove:
	rm -fr status_term turn_on turn_off temperature

status_term:
	gcc status_term.c -o status_term

turn_on:
	gcc turn_on_term.c -o turn_on

turn_off:
	gcc turn_off_term.c -o turn_off

temperature:
	gcc temperature.c -o temperature

