all: remove status_lamp turn_on turn_off

remove:
	rm -fr status_lamp turn_on turn_off

status_lamp:
	gcc status.c -o status_lamp

turn_on:
	gcc turn_on.c -o turn_on

turn_off:
	gcc turn_off.c -o turn_off

