all: remove status_radio turn_on turn_off volume station

remove:
	rm -fr status_radio turn_on turn_off volume station

status_radio:
	gcc status_radio.c -o status_radio

turn_on:
	gcc turn_on_radio.c -o turn_on

turn_off:
	gcc turn_off_radio.c -o turn_off

volume:
	gcc volume_radio.c -o volume

station:
	gcc station_radio.c -o station

